# Generated by Django 5.2.8 on 2025-11-19 22:40

import chats.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', chats.managers.UserManager()),
            ],
        ),
    ]
